Switch to peer default server, update workflow.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,26 +12,30 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Cleanup SSH Directory
-        run: rm -rf ~/.ssh
+      - name: Echo New Changes
+        run: echo 'New changes made to main'
+      
+      # THIS IS THE ACTUAL WORKFLOW FILE CONTENT
+      # - name: Cleanup SSH Directory
+      #   run: rm -rf ~/.ssh
 
-      - name: Install SSH Keys for Secure Connection
-        run: |
-          install -m 600 -D /dev/null ~/.ssh/id_rsa
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
+      # - name: Install SSH Keys for Secure Connection
+      #   run: |
+      #     install -m 600 -D /dev/null ~/.ssh/id_rsa
+      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+      #     ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
 
-      - name: Connect to Server, Pull Latest Code, and Rebuild Containers with Docker Script
-        run: |
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          set -e && \
-          echo 'Current directory: $(pwd)' && \
-          cd ${{ secrets.WORK_DIR }} && \
-          git checkout ${{ secrets.MAIN_BRANCH }} && \
-          git pull && \
-          chmod +x run_docker.sh && \
-          ./run_docker.sh prod \
-          exit"
+      # - name: Connect to Server, Pull Latest Code, and Rebuild Containers with Docker Script
+      #   run: |
+      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
+      #     set -e && \
+      #     echo 'Current directory: $(pwd)' && \
+      #     cd ${{ secrets.WORK_DIR }} && \
+      #     git checkout ${{ secrets.MAIN_BRANCH }} && \
+      #     git pull && \
+      #     chmod +x run_docker.sh && \
+      #     ./run_docker.sh prod \
+      #     exit"
 
-      - name: Cleanup SSH Keys
-        run: rm -rf ~/.ssh
+      # - name: Cleanup SSH Keys
+      #   run: rm -rf ~/.ssh
